### PR TITLE
stop using multiple <br's>

### PR DESCRIPTION
**Pull request by hriaksnv5678**
**Description:**

**Related Issue (if applicable):**

**Screenshots:**

### CODE REVIEW

**Comment by heybereket** [comment]
Nice find! :)

**Comment by heybereket** [comment]
@all-contributors add @hriaksnv5678 doc

**Comment by vishy-dev** [comment]
no dont

**Comment by vishy-dev** [comment]
it's my alt

**Comment by vishy-dev** [comment]
lol

**Pull request merged**
